# My notes
Get Datasets and get a rank at  Kaggle(https://www.kaggle.com)

kolla närmare på: Yupiter integration i vs code

### Hierarchy of needs
1. Collect: Instrumentation, logging, sensors, external data, user generated content
2. Move/Store: Relieble data flow, infrastructure, pipelines, etl structured, and undstryctured data
3. Explore/Transform: Cleaning, anomaly detection, prep
4. Aggregate/Label: Analytics, metrics, segments, aggregates, features, training data
5. Learn/Optimize: AB Testing, experimentation, simple ML Algorithms... AI & Deep learning

## Find help
- asdf

In [19]:
import pandas as pd
df = pd.DataFrame({'age': [3,29],'height': [94,170],'weight': [31,115]})
importedExcel = pd.read_excel("data/housing.xlsx")

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,3252-08-01 00:00:00,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,3014-08-01 00:00:00,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,2574-07-01 00:00:00,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,6431-05-01 00:00:00,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,8462-03-01 00:00:00,342200.0,NEAR BAY

In [20]:
importedCsv = pd.read_csv("data/housing.csv")
importedExcel.head(5)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,3252-08-01 00:00:00,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,3014-08-01 00:00:00,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,2574-07-01 00:00:00,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,6431-05-01 00:00:00,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,8462-03-01 00:00:00,342200.0,NEAR BAY