# Visualiserar medarbetares tillhörighet i olika team

In [17]:
import pandas as pd

In [18]:
teammembers = pd.read_excel("data/data.xlsx", 'TeamMembers')
teammembers.drop(['Typ', 'Användare','Department', 'Aktiv'], axis=1, inplace=True)
teammembers.dropna(thresh=2, inplace=True)
teammembers

                            Grupp                            E-post
1                  UK Development  Paul.Wadner-Holmes@skanska.co.uk
3                SE HR Pilotgrupp        torbjorn.kruger@skanska.se
4                Vsaa Förvaltning        susanne.sjoblom@skanska.se
8       UK User Access & Security           marc.winn@skanska.co.uk
10                 SE HR New Hire                isaken03@gmail.com
...                           ...                               ...
16352         SE Customer Support        ingela.sandberg@skanska.se
16353           HR Administration       pernilla.nilsson@skanska.se
16354              SE HR New Hire         micke.olsson@limegreen.se
16356  FI ITSM Littera hyväksyntä           esa.vaananen@skanska.fi
16357            SE HR Pilotgrupp        cecilia.mostrom@skanska.se

[11220 rows x 2 columns]

In [19]:
services = pd.read_excel("data/data.xlsx", 'Services')
services["Grupp"] = services["Supportgrupp (2nd)"]
services

,Namn,Ägare,Ansvarig,Förvaltningsobjekt,Supportgrupp (3rd),Supportgrupp (2nd),Grupp
0,Credit Safe - supplier import and credit report,Jessica Axelsson (SE343575),Alexander Janving (SE327069),Finans & Procurement,NaN,SE IT Fusion Procurement,SE IT Fusion Procurement
1,CAD/BIM Tools SE,Tomas Eklöf (SE316256),Tomas Eklöf (SE316256),Entreprenad,NaN,NaN,NaN
2,ACC SE - Autodesk Construction Cloud,Elina Wahlström (SE419080),Tomas Eklöf (SE316256),Entreprenad,NaN,SE IT ACC SWE,SE IT ACC SWE
3,Web County Orders Nyköping,Gabriella Rosén (SE402276),Gabriella Rosén (SE402276),TUI Customer Facing Services,NaN,NaN,NaN
4,Fusion Finance Finland,Martin Lönnqvist (FI249271),Kari Salokangas (FI60076),MO Finland Finance & Governance,SE IT Fusion AM,FI Fusion,FI Fusion
...,...,...,...,...,...,...,...
117,Birkamark Infrastructure,Jessica Axelsson (SE343575),Tomas Eklöf (SE316256),Finans & Procurement,NaN,2nd MS SQL-Infrastructure,2nd MS SQL-Infrastructure
118,Hjärnan,Mikael Ahlqvist (SE149184),Krister Normark (SE340049C),Business Platforms,NaN,SE IT 3rd VSAA - Decerno AB,SE IT 3rd VSAA - Decerno AB
119,Power Platform SE,Karam Chammas (SE313646),Kajsa Araskoug (SE427717),Digital Collaboration,SE IT 3rd Power Solutions,SE IT 3rd Power Solutions,SE IT 3rd Power Solutions
120,RPA AM,Jessica Axelsson (SE343575),Brindaduti Maiti (SE342434),Finans & Procurement,NaN,SE IT RPA AM,SE IT RPA AM
121,Fusion Database Platform,Mikael Ahlqvist (SE149184),Maria Jose Campo Martinez (SE312618),Business Platforms,SE IT Fusion TA & Deployment,SE IT Fusion TA & Deployment,SE IT Fusion TA & Deployment

In [20]:
df = pd.merge(services, teammembers, on='Grupp', how='inner')
df

,Namn,Ägare,Ansvarig,Förvaltningsobjekt,Supportgrupp (3rd),Supportgrupp (2nd),Grupp,E-post
0,Credit Safe - supplier import and credit report,Jessica Axelsson (SE343575),Alexander Janving (SE327069),Finans & Procurement,NaN,SE IT Fusion Procurement,SE IT Fusion Procurement,bhabani.sahoo@skanska.se
1,Credit Safe - supplier import and credit report,Jessica Axelsson (SE343575),Alexander Janving (SE327069),Finans & Procurement,NaN,SE IT Fusion Procurement,SE IT Fusion Procurement,jonas.edholm@skanska.se
2,Credit Safe - supplier import and credit report,Jessica Axelsson (SE343575),Alexander Janving (SE327069),Finans & Procurement,NaN,SE IT Fusion Procurement,SE IT Fusion Procurement,dayanidhi.mishra@skanska.se
3,Credit Safe - supplier import and credit report,Jessica Axelsson (SE343575),Alexander Janving (SE327069),Finans & Procurement,NaN,SE IT Fusion Procurement,SE IT Fusion Procurement,kishore.kadikalasadanandam@skanska.se
4,Credit Safe - supplier import and credit report,Jessica Axelsson (SE343575),Alexander Janving (SE327069),Finans & Procurement,NaN,SE IT Fusion Procurement,SE IT Fusion Procurement,aniket.patil@skanska.se
...,...,...,...,...,...,...,...,...
721,Hjärnan,Mikael Ahlqvist (SE149184),Krister Normark (SE340049C),Business Platforms,NaN,SE IT 3rd VSAA - Decerno AB,SE IT 3rd VSAA - Decerno AB,mustafa.elomeiri@skanska.se
722,RPA AM,Jessica Axelsson (SE343575),Brindaduti Maiti (SE342434),Finans & Procurement,NaN,SE IT RPA AM,SE IT RPA AM,brinda.maiti@skanska.se
723,RPA AM,Jessica Axelsson (SE343575),Brindaduti Maiti (SE342434),Finans & Procurement,NaN,SE IT RPA AM,SE IT RPA AM,swati.jadhav@skanska.se
724,RPA AM,Jessica Axelsson (SE343575),Brindaduti Maiti (SE342434),Finans & Procurement,NaN,SE IT RPA AM,SE IT RPA AM,deepak.patil@skanska.se
725,RPA AM,Jessica Axelsson (SE343575),Brindaduti Maiti (SE342434),Finans & Procurement,NaN,SE IT RPA AM,SE IT RPA AM,linus.ljungberg@skanska.se

In [21]:
sample = services["Namn"].drop_duplicates() #.sample(10)
dataview = df[df['Namn'].isin(sample)]
dataview = dataview.drop(['Ägare', 'Ansvarig','Förvaltningsobjekt', 'Supportgrupp (3rd)', 'Supportgrupp (2nd)'], axis=1)
dataview = dataview.rename(columns={"Namn": "Service", "Grupp": "Team", "E-post": "E-post"})
dataview

,Service,Team,E-post
0,Credit Safe - supplier import and credit report,SE IT Fusion Procurement,bhabani.sahoo@skanska.se
1,Credit Safe - supplier import and credit report,SE IT Fusion Procurement,jonas.edholm@skanska.se
2,Credit Safe - supplier import and credit report,SE IT Fusion Procurement,dayanidhi.mishra@skanska.se
3,Credit Safe - supplier import and credit report,SE IT Fusion Procurement,kishore.kadikalasadanandam@skanska.se
4,Credit Safe - supplier import and credit report,SE IT Fusion Procurement,aniket.patil@skanska.se
...,...,...,...
721,Hjärnan,SE IT 3rd VSAA - Decerno AB,mustafa.elomeiri@skanska.se
722,RPA AM,SE IT RPA AM,brinda.maiti@skanska.se
723,RPA AM,SE IT RPA AM,swati.jadhav@skanska.se
724,RPA AM,SE IT RPA AM,deepak.patil@skanska.se
725,RPA AM,SE IT RPA AM,linus.ljungberg@skanska.se

In [22]:
# Visualize teams and members
teams = dataview.drop(['Service'], axis=1)
teams = teams.drop_duplicates()
for i, row in teams.iterrows():
    antal = teams[teams["E-post"] ==teams.at[i,"E-post"]]["E-post"].count()
    teams.at[i,'Amount'] = 1/antal
teams

,Team,E-post,Amount
0,SE IT Fusion Procurement,bhabani.sahoo@skanska.se,0.500000
1,SE IT Fusion Procurement,jonas.edholm@skanska.se,0.333333
2,SE IT Fusion Procurement,dayanidhi.mishra@skanska.se,0.500000
3,SE IT Fusion Procurement,kishore.kadikalasadanandam@skanska.se,0.333333
4,SE IT Fusion Procurement,aniket.patil@skanska.se,0.500000
...,...,...,...
721,SE IT 3rd VSAA - Decerno AB,mustafa.elomeiri@skanska.se,0.500000
722,SE IT RPA AM,brinda.maiti@skanska.se,1.000000
723,SE IT RPA AM,swati.jadhav@skanska.se,1.000000
724,SE IT RPA AM,deepak.patil@skanska.se,1.000000
725,SE IT RPA AM,linus.ljungberg@skanska.se,0.500000

In [23]:
import networkx as nx
import numpy as np
from pyvis.network import Network

team_members = pd.DataFrame(
    {
        "source": teams["E-post"].tolist(),
        "target": teams["Team"].tolist(),
        "weight": teams["Amount"].tolist()
    }
)
G_team_members = nx.from_pandas_edgelist(team_members, edge_attr=True)
net = Network(notebook=True)
for source in team_members['source'].unique():
    net.add_node(source, label=source)
for target in team_members['target'].unique():
    net.add_node(target, label=target, color='red')
for index, row in team_members.iterrows():
    net.add_edge(row['source'], row['target'], value=row['weight']/3, color='gray')
net.show("team_members.html")

Warning: When  cdn_resources is 'local' jupyter notebook has issues displaying graphics on chrome/safari. Use cdn_resources='in_line' or cdn_resources='remote' if you have issues viewing graphics in a notebook.
team_members.html

In [24]:

with open("team_members.html", "r") as file:
    html_data = file.read()

start = html_data.find("nodes =")
end = html_data.find("nodeColors = {};")
javascript_data = html_data[start:end].strip()
javascript_data = javascript_data.replace("nodes = ", "team_nodes = ")
javascript_data = javascript_data.replace("edges = ", "team_edges = ")
file = open("data/team_members.js", "wt") #(r)ead, (a)ppend, (w)rite, create(x) (t)ext/(b)inary
file.write(javascript_data)
file.close()

import os
os.remove("team_members.html")